- contracts/optimistic-ethereum/OVM/chain/OVM_CanonicalTransactionChain.sol
- contracts/optimistic-ethereum/iOVM/chain/iOVM_CanonicalTransactionChain.sol
- test/contracts/OVM/chain/OVM_CanonicalTransactionChain.spec.ts
Fixes the events to make parsing easier
> Fix ctc events

- contracts/optimistic-ethereum/OVM/OVM_BondManager.sol
- contracts/optimistic-ethereum/OVM/OVM_FraudContributor.sol
- contracts/optimistic-ethereum/OVM/chain/OVM_CanonicalTransactionChain.sol
- contracts/optimistic-ethereum/OVM/chain/OVM_StateCommitmentChain.sol
- contracts/optimistic-ethereum/OVM/verification/OVM_FraudVerifier.sol
- contracts/optimistic-ethereum/OVM/verification/OVM_StateTransitioner.sol
- contracts/test-helpers/Mock_FraudVerifier.sol
- contracts/test-helpers/TestERC20.sol
- test/bond.ts
- test/contracts/OVM/chain/OVM_StateCommitmentChain.spec.ts
- test/contracts/OVM/verification/OVM_FraudVerifier.spec.ts
- test/contracts/OVM/verification/OVM_StateTransitioner.spec.ts
- test/helpers/dummy/batches.ts
Enables submitting fidelity bonds by the sequencers which they forfeit in cause of fraud. The reward gets distributed proportionally to all the users that provided witness for the dispute resolution.
> Bond Manager

- contracts/optimistic-ethereum/OVM/chain/OVM_CanonicalTransactionChain.sol
- contracts/optimistic-ethereum/iOVM/chain/iOVM_CanonicalTransactionChain.sol
- test/contracts/OVM/chain/OVM_CanonicalTransactionChain.spec.ts
This PR adds the correct encoding for `appendSequencerBatch`
> Add correct encoding

- contracts/optimistic-ethereum/OVM/chain/OVM_CanonicalTransactionChain.sol
- contracts/optimistic-ethereum/iOVM/chain/iOVM_CanonicalTransactionChain.sol
- test/contracts/OVM/chain/OVM_CanonicalTransactionChain.spec.ts
Add the total elements to the event emission to make it easier to sync.
> Emit tx index

- contracts/optimistic-ethereum/OVM/chain/OVM_CanonicalTransactionChain.sol
- contracts/optimistic-ethereum/OVM/execution/OVM_ExecutionManager.sol
- contracts/optimistic-ethereum/iOVM/execution/iOVM_ExecutionManager.sol
- contracts/optimistic-ethereum/libraries/codec/Lib_OVMCodec.sol
- test/contracts/OVM/chain/OVM_CanonicalTransactionChain.spec.ts
- test/helpers/dummy/transactions.ts
- test/helpers/test-runner/test-runner.ts
> Add verify transaction

- contracts/optimistic-ethereum/OVM/chain/OVM_CanonicalTransactionChain.sol
Removes an unused byte in our encoding for the leaf hash.
> Remove unused byte in encoding

- contracts/optimistic-ethereum/OVM/bridge/OVM_L1CrossDomainMessenger.sol
- contracts/optimistic-ethereum/OVM/bridge/OVM_L2CrossDomainMessenger.sol
- contracts/optimistic-ethereum/OVM/chain/OVM_CanonicalTransactionChain.sol
- contracts/optimistic-ethereum/OVM/chain/OVM_StateCommitmentChain.sol
- contracts/optimistic-ethereum/OVM/execution/OVM_ExecutionManager.sol
- contracts/optimistic-ethereum/OVM/verification/OVM_StateTransitioner.sol
- contracts/optimistic-ethereum/iOVM/chain/iOVM_StateCommitmentChain.sol
- contracts/optimistic-ethereum/libraries/utils/Lib_RingBuffer.sol
- contracts/test-helpers/Helper_SimpleProxy.sol
- test/contracts/OVM/chain/OVM_StateCommitmentChain.spec.ts
- test/contracts/libraries/rlp/Lib_RLPReader.spec.ts
PR changes `StateCommitmentChain` to require that users provide a height for their batches, also introduces a window during which only the `sequencer` can submit state batches as a temporary way to make breaking bugs less annoying.
> Require height specification in SCC

- contracts/optimistic-ethereum/OVM/chain/OVM_CanonicalTransactionChain.sol
- test/contracts/OVM/chain/OVM_CanonicalTransactionChain.spec.ts
The last PR to remove the unused zero byte didn't actually remove it. This time I'm actually getting rid of it.
> Actually remove unused byte

- contracts/optimistic-ethereum/iOVM/accounts/iOVM_ECDSAContractAccount.sol
- contracts/optimistic-ethereum/iOVM/bridge/iOVM_BaseCrossDomainMessenger.sol
- contracts/optimistic-ethereum/iOVM/bridge/iOVM_L1CrossDomainMessenger.sol
- contracts/optimistic-ethereum/iOVM/bridge/iOVM_L2CrossDomainMessenger.sol
- contracts/optimistic-ethereum/iOVM/chain/iOVM_CanonicalTransactionChain.sol
- contracts/optimistic-ethereum/iOVM/chain/iOVM_StateCommitmentChain.sol
- contracts/optimistic-ethereum/iOVM/execution/iOVM_ExecutionManager.sol
- contracts/optimistic-ethereum/iOVM/execution/iOVM_SafetyChecker.sol
- contracts/optimistic-ethereum/iOVM/execution/iOVM_StateManager.sol
- contracts/optimistic-ethereum/iOVM/execution/iOVM_StateManagerFactory.sol
- contracts/optimistic-ethereum/iOVM/precompiles/iOVM_DeployerWhitelist.sol
- contracts/optimistic-ethereum/iOVM/precompiles/iOVM_L1MessageSender.sol
- contracts/optimistic-ethereum/iOVM/precompiles/iOVM_L2ToL1MessagePasser.sol
- contracts/optimistic-ethereum/iOVM/verification/iOVM_BondManager.sol
- contracts/optimistic-ethereum/iOVM/verification/iOVM_FraudVerifier.sol
- contracts/optimistic-ethereum/iOVM/verification/iOVM_StateTransitioner.sol
- contracts/optimistic-ethereum/iOVM/verification/iOVM_StateTransitionerFactory.sol
Changes interface versions to support older Solidity releases.
> Experimenting with multiple sol versions

- bin/deploy.js
- package.json
Not all `env` programs support `-S` flag
> deploy portability

- bin/deploy.js
Log the address manager address
> deployer: log address manager address

- contracts/optimistic-ethereum/OVM/chain/OVM_CanonicalTransactionChain.sol
- contracts/optimistic-ethereum/iOVM/chain/iOVM_CanonicalTransactionChain.sol
> Add getPendingQueueElements

- contracts/optimistic-ethereum/OVM/bridge/OVM_BaseCrossDomainMessenger.sol
- contracts/optimistic-ethereum/iOVM/bridge/iOVM_BaseCrossDomainMessenger.sol
- package.json
> add xdomainmessenger to interface

- bin/deploy.js
- Adds more addresses to output
> deployer: add more addresses to the output

- bin/deploy.js
Correctly deploy with the layer 2 script
> deploy: use layer 2 chainid

- buidler.config.ts
- contracts/optimistic-ethereum/OVM/bridge/OVM_L1CrossDomainMessenger.sol
- contracts/optimistic-ethereum/OVM/bridge/OVM_L2CrossDomainMessenger.sol
- contracts/optimistic-ethereum/OVM/chain/OVM_CanonicalTransactionChain.sol
- contracts/optimistic-ethereum/OVM/chain/OVM_StateCommitmentChain.sol
- contracts/optimistic-ethereum/OVM/execution/OVM_ExecutionManager.sol
- contracts/optimistic-ethereum/OVM/verification/OVM_BondManager.sol
- contracts/optimistic-ethereum/OVM/verification/OVM_FraudContributor.sol
- contracts/optimistic-ethereum/OVM/verification/OVM_FraudVerifier.sol
- contracts/optimistic-ethereum/OVM/verification/OVM_StateTransitioner.sol
- contracts/optimistic-ethereum/iOVM/chain/iOVM_CanonicalTransactionChain.sol
- contracts/optimistic-ethereum/iOVM/chain/iOVM_StateCommitmentChain.sol
- package.json
- src/contract-deployment/config.ts
- src/contract-deployment/deploy.ts
- test/contracts/OVM/chain/OVM_CanonicalTransactionChain.spec.ts
- test/contracts/OVM/chain/OVM_StateCommitmentChain.spec.ts
- test/contracts/OVM/verification/OVM_FraudVerifier.spec.ts
Removes the proxies from the contracts so `msg.sender` is correct
> feat: no proxy

- .github/workflows/dockerhub-build-push.yml
Adds build and push to dockerhub for deployer docker image
> gitflows: add push to dockerhub

- bin/deploy.js
- package.json
- yarn.lock
Adds ledger support to the deployer script
Depends on https://github.com/ethereum-optimism/docker/pull/7
> deployer: ledger support, no sequencer private key

- contracts/optimistic-ethereum/OVM/bridge/OVM_BaseCrossDomainMessenger.sol
- contracts/optimistic-ethereum/iOVM/bridge/iOVM_BaseCrossDomainMessenger.sol
- contracts/optimistic-ethereum/mockOVM/bridge/mockOVM_CrossDomainMessenger.sol
- package.json
> Update mock messengers

- contracts/optimistic-ethereum/OVM/bridge/OVM_L1CrossDomainMessenger.sol
- contracts/optimistic-ethereum/libraries/resolver/Lib_ResolvedDelegateProxy.sol
- src/contract-deployment/config.ts
- test/contracts/OVM/bridge/OVM_L1CrossDomainMessenger.spec.ts
- test/contracts/libraries/trie/Lib_MerkleTrie.spec.ts
- test/contracts/libraries/trie/Lib_SecureMerkleTrie.spec.ts
Adds a proxy for the L1Messenger!
- Any objections with the way that I tested the proxy? Basically just used it for the L1Messenger tests.
- Fixes https://github.com/ethereum-optimism/roadmap/issues/147
> Add messenger proxy

- contracts/optimistic-ethereum/OVM/accounts/OVM_ECDSAContractAccount.sol
- test/contracts/OVM/accounts/OVM_ECDSAContractAccount.spec.ts
> Add fee to EOA

- src/contract-deployment/config.ts
> Fix deployment bug

- contracts/optimistic-ethereum/OVM/bridge/OVM_BaseCrossDomainMessenger.sol
- contracts/optimistic-ethereum/OVM/bridge/OVM_L1CrossDomainMessenger.sol
- contracts/optimistic-ethereum/OVM/bridge/OVM_L2CrossDomainMessenger.sol
- contracts/optimistic-ethereum/iOVM/bridge/iOVM_BaseCrossDomainMessenger.sol
> Add events to xDomain messengers

- .github/workflows/dockerhub-build-push.yml
Updates the version of `webfactory/ssh-agent`
> workflows: update ssh-agent

- contracts/optimistic-ethereum/OVM/accounts/OVM_ProxyEOA.sol
- test/contracts/OVM/accounts/OVM_ProxyEOA.spec.ts
- test/contracts/OVM/execution/OVM_ExecutionManager/ovmCREATEEOA.spec.ts
Little PR to remove a footgun if future users' smart contract wallets are stateful.
> Use less common slot for EOA implementation

- src/contract-deployment/config.ts
- src/contract-dumps.ts
> update precompile addresses

- contracts/optimistic-ethereum/libraries/utils/Lib_MerkleUtils.sol
Fixes a small a bug in the way we compute our default hashes.
> Small fix for MerkleUtils

- contracts/optimistic-ethereum/OVM/accounts/OVM_ECDSAContractAccount.sol
- contracts/optimistic-ethereum/mockOVM/accounts/mockOVM_ECDSAContractAccount.sol
- test/contracts/OVM/accounts/OVM_ECDSAContractAccount.spec.ts
- test/helpers/codec/encoding.ts
https://github.com/ethereum-optimism/roadmap/issues/191
> chainId check

- contracts/optimistic-ethereum/libraries/utils/Lib_BytesUtils.sol
from: github.com/GNSPS/solidity-bytes-utils/blob/feat/update-0.7.0/contracts/BytesLib.sol
- 
-
-
- Fixes https://github.com/ethereum-optimism/roadmap/issues/195
> critical bounds bug for slice

- contracts/optimistic-ethereum/OVM/chain/OVM_CanonicalTransactionChain.sol
- Fixes 
https://github.com/ethereum-optimism/roadmap/issues/197
> queueindex

- contracts/optimistic-ethereum/OVM/chain/OVM_CanonicalTransactionChain.sol
- contracts/optimistic-ethereum/OVM/verification/OVM_StateTransitioner.sol
- contracts/optimistic-ethereum/iOVM/chain/iOVM_CanonicalTransactionChain.sol
- contracts/optimistic-ethereum/iOVM/verification/iOVM_BondManager.sol
- contracts/optimistic-ethereum/mockOVM/verification/mockOVM_BondManager.sol
Adds a few contract changes necessary to get the fraud prover to work. Also includes a hotfix for a bug with the `mockOVM_BondManager` and its interaction with another recently merged PR.
> Adds contract changes necessary for fraud prover

- contracts/optimistic-ethereum/OVM/execution/OVM_ExecutionManager.sol
- Fixes # https://github.com/ethereum-optimism/roadmap/issues/225
> remove nonce check from ovmSETNONCE

- contracts/optimistic-ethereum/libraries/utils/Lib_EthUtils.sol
- Fixes # https://github.com/ethereum-optimism/roadmap/issues/259
> remove dupe toAddress

- contracts/optimistic-ethereum/OVM/verification/OVM_FraudVerifier.sol
- test/contracts/OVM/verification/OVM_FraudVerifier.spec.ts
- Fixes # https://github.com/ethereum-optimism/roadmap/issues/257
> global root index check

- contracts/optimistic-ethereum/OVM/chain/OVM_CanonicalTransactionChain.sol
- test/contracts/OVM/chain/OVM_CanonicalTransactionChain.spec.ts
- test/contracts/OVM/verification/OVM_FraudVerifier.spec.ts
- test/contracts/libraries/trie/Lib_MerkleTrie.spec.ts
> Remove incorrect validate batch context call

- contracts/optimistic-ethereum/OVM/accounts/OVM_ECDSAContractAccount.sol
- test/contracts/OVM/accounts/OVM_ECDSAContractAccount.spec.ts
- Fixes https://github.com/ethereum-optimism/roadmap/issues/223
> require relayer fee transfer success

- buidler.config.ts
- contracts/optimistic-ethereum/OVM/bridge/OVM_BaseCrossDomainMessenger.sol
- contracts/optimistic-ethereum/OVM/bridge/OVM_L2CrossDomainMessenger.sol
- contracts/optimistic-ethereum/iOVM/bridge/iOVM_BaseCrossDomainMessenger.sol
- contracts/optimistic-ethereum/iOVM/bridge/iOVM_L2CrossDomainMessenger.sol
- contracts/optimistic-ethereum/iOVM/precompiles/iOVM_L1MessageSender.sol
- contracts/optimistic-ethereum/iOVM/precompiles/iOVM_L2ToL1MessagePasser.sol
- contracts/optimistic-ethereum/libraries/resolver/Lib_AddressManager.sol
- contracts/optimistic-ethereum/libraries/resolver/Lib_AddressResolver.sol
- contracts/optimistic-ethereum/libraries/resolver/Lib_Ownable.sol
- contracts/optimistic-ethereum/libraries/utils/Lib_ReentrancyGuard.sol
- package.json
- plugins/buidler/ovm-compiler.ts
- src/contract-defs.ts
- tsconfig.json
- yarn.lock
Title says it all. Adds a buidler plugin for compiling both EVM and OVM contracts.
> Adds an ovm compilation plugin, compiles into artifacts and artifacts/ovm

- bin/deploy.js
> Add L2 ETH config for deploy

- contracts/optimistic-ethereum/OVM/bridge/OVM_BaseCrossDomainMessenger.sol
- Fixes https://github.com/ethereum-optimism/roadmap/issues/280
> Mark base contracts as abstract

- contracts/optimistic-ethereum/OVM/execution/OVM_ExecutionManager.sol
- Fixes https://github.com/ethereum-optimism/roadmap/issues/277
> use getCodeHash

- contracts/optimistic-ethereum/OVM/chain/OVM_StateCommitmentChain.sol
- contracts/optimistic-ethereum/OVM/execution/OVM_ExecutionManager.sol
- contracts/optimistic-ethereum/libraries/codec/Lib_OVMCodec.sol
- Fixes https://github.com/ethereum-optimism/roadmap/issues/265
> Comment fixes

- contracts/optimistic-ethereum/libraries/rlp/Lib_RLPWriter.sol
- Fixes https://github.com/ethereum-optimism/roadmap/issues/264
> OZ L09 Remove unnecessary use of assembly

- contracts/optimistic-ethereum/OVM/accounts/OVM_ECDSAContractAccount.sol
- test/contracts/OVM/accounts/OVM_ECDSAContractAccount.spec.ts
Minor fix, disabling gas checks for now.
> Temporarily disable gas checks

- .github/workflows/integration.yml
Runs the integration tests against the contracts to prevent regressions
> gitflows: run integration tests

- contracts/optimistic-ethereum/libraries/utils/Lib_BytesUtils.sol
- Fixes https://github.com/ethereum-optimism/roadmap/issues/278
> Simplify Casting

- contracts/optimistic-ethereum/libraries/codec/Lib_OVMCodec.sol
- contracts/test-libraries/codec/TestLib_OVMCodec.sol
- test/contracts/libraries/codec/Lib_OVMCodec.spec.ts
> Update codec to pull chain id from EM

- package.json
> Bump version to .14

- buidler.config.ts
- contracts/optimistic-ethereum/OVM/bridge/OVM_BaseCrossDomainMessenger.sol
- contracts/optimistic-ethereum/OVM/bridge/OVM_L1CrossDomainMessenger.sol
- contracts/optimistic-ethereum/OVM/bridge/OVM_L2CrossDomainMessenger.sol
- contracts/optimistic-ethereum/OVM/chain/OVM_CanonicalTransactionChain.sol
- contracts/optimistic-ethereum/OVM/precompiles/OVM_ETH.sol
- contracts/optimistic-ethereum/OVM/precompiles/OVM_L2ToL1MessagePasser.sol
- contracts/optimistic-ethereum/iOVM/bridge/iOVM_BaseCrossDomainMessenger.sol
- contracts/optimistic-ethereum/iOVM/bridge/iOVM_L1CrossDomainMessenger.sol
- contracts/optimistic-ethereum/iOVM/bridge/iOVM_L2CrossDomainMessenger.sol
- contracts/optimistic-ethereum/iOVM/execution/iOVM_StateManager.sol
- contracts/optimistic-ethereum/iOVM/precompiles/iOVM_DeployerWhitelist.sol
- contracts/optimistic-ethereum/iOVM/precompiles/iOVM_ERC20.sol
- contracts/optimistic-ethereum/iOVM/precompiles/iOVM_L1MessageSender.sol
- contracts/optimistic-ethereum/iOVM/precompiles/iOVM_L2ToL1MessagePasser.sol
- contracts/optimistic-ethereum/iOVM/verification/iOVM_BondManager.sol
- contracts/optimistic-ethereum/iOVM/verification/iOVM_StateTransitioner.sol
- contracts/optimistic-ethereum/libraries/codec/Lib_OVMCodec.sol
- contracts/optimistic-ethereum/libraries/resolver/Lib_AddressManager.sol
- contracts/optimistic-ethereum/libraries/resolver/Lib_AddressResolver.sol
- contracts/optimistic-ethereum/libraries/resolver/Lib_Ownable.sol
- contracts/optimistic-ethereum/libraries/trie/Lib_SecureMerkleTrie.sol
- contracts/optimistic-ethereum/libraries/utils/Lib_ReentrancyGuard.sol
- test/contracts/OVM/chain/OVM_CanonicalTransactionChain.spec.ts
- test/contracts/OVM/execution/OVM_ExecutionManager/ovmCREATEEOA.spec.ts
> Merge master into freeze integration branch 

- bin/deploy.js
- src/contract-deployment/config.ts
> [code freeze] Fix deploy script

- contracts/optimistic-ethereum/OVM/precompiles/OVM_DeployerWhitelist.sol
> Use Lib_SafeExecutionManagerWrapper for predeploy

- bin/deploy.js
- src/contract-deployment/config.ts
- src/contract-dumps.ts
Configure the authentication for the `OVM_L2MessageRelayer`
> relayer: add to config

- bin/take-dump.ts
- package.json
- src/contract-dumps.ts
Enable config for state dump parameters
> state dump: allow for config

- bin/deploy.js
Fixes an issue around relayer authentication where the relayer address can now be configured and is set to the zero address by default, meaning there is no withdrawal authentication
> deploy: fix relayer address config

- .github/workflows/tag-release.yml
- CHANGELOG.md
Adds an initial `CHANGELOG.md` and the automation script for publishing releases on tag pushes + docker image pushes
> release: add changelog + automation

- package.json
Bumps the version to `0.1.0` for release
> version: bump to 0.1.0

- test/contracts/OVM/chain/OVM_CanonicalTransactionChain.spec.ts
Quick PR to un-`skip` some CTC tests which somehow had become skipped.
> Re-enable CTC monotonicity Tests

- contracts/optimistic-ethereum/libraries/resolver/Lib_AddressManager.sol
Tiny PR to emit an event when addresses are updated for maximum transparency.
> Add Events for Address Management

- CHANGELOG.md
- package.json
I messed up and didn't clean / build right before the publish. Redoing this so that it's not a broken dep. Also, we need to automate this npm publish process omg.
- 
-
-
> version: bump to 0.1.2

- contracts/optimistic-ethereum/OVM/verification/OVM_FraudVerifier.sol
- contracts/optimistic-ethereum/iOVM/verification/iOVM_FraudVerifier.sol
Very simple patch. We really need these events!
> Added events to the fraud verifier

- CHANGELOG.md
- package.json
> version: bump to 0.1.3

- package.json
> mainnet chain id 422 -> 10

- CHANGELOG.md
- package.json
> version: bump to 0.1.5

- contracts/optimistic-ethereum/OVM/bridge/ETH/OVM_L1ETHGateway.sol
- contracts/optimistic-ethereum/OVM/bridge/OVM_CrossChainEnabled.sol
- contracts/optimistic-ethereum/iOVM/bridge/ERC20/iWETH.sol
- contracts/optimistic-ethereum/iOVM/bridge/ETH/iOVM_L1ETHGateway.sol
- test/contracts/OVM/bridge/ETH/OVM_L1ETHGateway.spec.ts
> Add ETH deposit gateway (OVM_L1ETHGateway)

- package.json
Version bump for publish to npm
> version: 0.1.6

- .github/workflows/build-test-lint-contracts.yml
- yarn.lock
Rebuilds lockfile so that BigNumber implementations are consistent between ethers stuff.  See: https://github.com/ethers-io/ethers.js/issues/1293
> Rebuild lockfile

- package.json
- yarn.lock
Fixes `ethers` and some other dependencies.
- Fixes #235
> Fix some broken dependencies

- package.json
Will publish and tag this release on merge
> version: 0.1.7

- contracts/optimistic-ethereum/OVM/execution/OVM_ExecutionManager.sol
Adds `simulateMessage` to the execution manager to be used with `eth_call`
Must be used with geth here: https://github.com/ethereum-optimism/go-ethereum/pull/210
>  feat/simulate message

- package.json
> version: v0.1.8

- CHANGELOG.md
- package.json
> version: v0.1.9

- .github/workflows/push-to-integration-repo.yml
Push to integrations repo on merge
> gitflow: push to integrations repo

- contracts/optimistic-ethereum/libraries/bridge/OVM_CrossDomainEnabled.sol
> Increase default deposit gaslimit

- .github/workflows/integration.yml
> [Fix] CI on merge

- contracts/optimistic-ethereum/iOVM/bridge/tokens/iOVM_L2DepositedERC20.sol
> remove uniswapv2ERC20 interface import

- .github/workflows/tag-release.yml
Creates a commit on https://github.com/ethereum-optimism/regenesis when a new Docker image is successfully built and pushed to Docker hub that contains the state dump, labelled using the same tag.
This is implemented as a new job on the [Create Releases on Tags](https://github.com/ethereum-optimism/contracts/actions/workflows/tag-release.yml) Github Action to take advantage of the fact that (1) that workflow only runs when a new tag is created and (2) it already builds the state dump in the `docker` job so we can re-use it.
The `docker` job now stores the state dump as an artifacts on the Github Action: https://github.com/ethereum-optimism/contracts/blob/34724a1e553623f2f68ff5adb6728d0c4f7f1abb/.github/workflows/tag-release.yml#L48-L52
The `git` job will read that artifact and create a …
> Commit state dumps to regenesis repo for new tags

- package.json
- tslint.json
- yarn.lock
Reverts ethereum-optimism/contracts#221
> Revert "Use @eth-optimism/dev"

- CHANGELOG.md
- package.json
> release v0.1.10

- contracts/optimistic-ethereum/OVM/execution/OVM_StateManager.sol
Small PR for standardizing the state manager.
> cleanup: Minor cleanup to state manager

- .github/CODEOWNERS
> dev: Create CODEOWNERS

- contracts/optimistic-ethereum/libraries/utils/Lib_Bytes32Utils.sol
> cleanup: Bytes32Utils

- contracts/optimistic-ethereum/OVM/execution/OVM_StateManagerFactory.sol
> cleanup: Minor cleanups for StateManagerFactory

- contracts/optimistic-ethereum/OVM/accounts/OVM_ProxyEOA.sol
Minor cleanups and reducing error surface.
> cleanup: Proxy_EOA

- contracts/optimistic-ethereum/OVM/accounts/OVM_ECDSAContractAccount.sol
> cleanup: ECDSAContractAccount

- .github/workflows/tag-release.yml
Resolving the bug that prevented us from autopublishing. 
Note: Two areas for improvement I didn't include:
- A README update on how this works and expectations, outlined by @snario in [this comment](https://github.com/ethereum-optimism/contracts/pull/261#issuecomment-789757260)
- `.vscode` package recommendations that we internally discussed which will prevent bugs like this in the future
Both are considering how I won't be working extensively in this repo soon, so leaving this up to code owners! Feel free to push those changes to this branch.
- 
-
-
> [Fix] Autopublish workflow bug

- contracts/optimistic-ethereum/OVM/chain/OVM_CanonicalTransactionChain.sol
- test/contracts/OVM/chain/OVM_CanonicalTransactionChain.spec.ts
Optimization to the optimization
> Optimization: Conditional Monotonicity Checking

- contracts/optimistic-ethereum/OVM/bridge/tokens/OVM_L1ETHGateway.sol
> removed unused import and updated comments

- contracts/optimistic-ethereum/OVM/bridge/tokens/OVM_L1ETHGateway.sol
Update confusing comment on `finalizeWithdrawal()`.
- Fixes #334
> Fix confusing comment on finalizeWithdrawal()

- contracts/optimistic-ethereum/libraries/utils/Lib_MerkleTree.sol
> Fix shortcut for single element

- contracts/optimistic-ethereum/OVM/bridge/tokens/OVM_L1ETHGateway.sol
- contracts/optimistic-ethereum/libraries/resolver/Lib_ResolvedDelegateProxy.sol
- src/contract-deployment/config.ts
- test/contracts/OVM/bridge/assets/OVM_L1ETHGateway.spec.ts
A clear and concise description of the features you're adding in this pull request.
**Additional context**
Add any other context about the problem you're solving.
**Metadata**
- Fixes #[Link to Issue]
> Add OVM_L1ETHGateway Proxy

- .github/workflows/build-test-lint-contracts.yml
- package.json
- yarn.lock
Just some minor tweaks to `package.json`. Moves some dependencies over to `devDependencies` to reduce install size. Also makes sure that `lint` will run `lint:fix` before running `lint:check` to make developer lives a bit easier. Since this will have an impact on CI, I also updated `build-test-lint-contracts.yml` to run `lint:check` instead of `lint`.
> dev: Minor cleanup to package.json and remove unused deps

- package.json
A clear and concise description of the features you're adding in this pull request.
**Additional context**
Add any other context about the problem you're solving.
**Metadata**
- Fixes #[Link to Issue]
> Publish version 0.2.0 🥳

- contracts/optimistic-ethereum/libraries/resolver/Lib_ResolvedDelegateProxy.sol
> cleanup: Minor cleanup to ResolvedDelegateProxy

- contracts/optimistic-ethereum/libraries/resolver/Lib_AddressResolver.sol
Just doing some minor cleanup while I'm bored.
> cleanup: Minor cleanup to address resolver

- contracts/optimistic-ethereum/libraries/resolver/Lib_AddressManager.sol
Just doing some cleanup while I'm bored.
> cleanup: Minor cleanup to address manager
