ethereum-optimism/contracts

bin/take-dump.ts
contracts/optimistic-ethereum/OVM/bridge/OVM_BaseCrossDomainMessenger.sol
contracts/optimistic-ethereum/OVM/bridge/OVM_L1CrossDomainMessenger.sol
contracts/optimistic-ethereum/OVM/bridge/OVM_L2CrossDomainMessenger.sol
contracts/optimistic-ethereum/OVM/chain/OVM_BaseChain.sol
contracts/optimistic-ethereum/OVM/chain/OVM_CanonicalTransactionChain.sol
contracts/optimistic-ethereum/OVM/chain/OVM_StateCommitmentChain.sol
contracts/optimistic-ethereum/iOVM/bridge/iOVM_BaseCrossDomainMessenger.sol
contracts/optimistic-ethereum/iOVM/chain/iOVM_StateCommitmentChain.sol
contracts/optimistic-ethereum/libraries/codec/Lib_OVMCodec.sol
contracts/optimistic-ethereum/mockOVM/bridge/mockOVM_CrossDomainMessenger.sol
package.json
src/contract-deployment/config.ts
src/contract-deployment/deploy.ts
src/contract-dumps.ts
src/index.ts
test/contracts/OVM/chain/OVM_StateCommitmentChain.spec.ts
test/contracts/OVM/execution/OVM_ExecutionManager/ovmCREATE.spec.ts
test/helpers/dummy/batches.ts
test/helpers/test-runner/test-runner.ts
tsconfig.json
yarn.lock

Adds `timestamp` to `ChainBatchHeader` and uses the value to assert that a message is outside of the fraud proof window. Also adds authentication to the message passing contracts via `AddressManager`/`AddressResolver` pattern.

Add timestamp and auth to message passing contracts

---

contracts/optimistic-ethereum/OVM/execution/OVM_ExecutionManager.sol
contracts/optimistic-ethereum/OVM/execution/OVM_StateManager.sol
contracts/optimistic-ethereum/OVM/verification/OVM_StateTransitioner.sol
contracts/optimistic-ethereum/iOVM/execution/iOVM_StateManager.sol
contracts/optimistic-ethereum/libraries/resolver/Lib_AddressManager.sol
contracts/optimistic-ethereum/libraries/resolver/Lib_Ownable.sol
test/helpers/test-runner/test-runner.ts

Makes `OVM_StateManager` usage within `run` authenticated.

Made StateManager usage authenticated

---

src/contract-deployment/config.ts

Fixes a bug in `yarn build` which prevents the command from exiting cleanly

bufix: deploy script

---

contracts/optimistic-ethereum/OVM/bridge/OVM_L1CrossDomainMessenger.sol
contracts/optimistic-ethereum/OVM/bridge/OVM_L2CrossDomainMessenger.sol
contracts/optimistic-ethereum/OVM/precompiles/OVM_DeployerWhitelist.sol
contracts/optimistic-ethereum/OVM/precompiles/OVM_L1MessageSender.sol
contracts/optimistic-ethereum/OVM/precompiles/OVM_L2ToL1MessagePasser.sol
test/contracts/OVM/bridge/OVM_L1CrossDomainMessenger.spec.ts
test/contracts/OVM/precompiles/OVM_L2ToL1MessagePasser.spec.ts

Replaces `L2ToL1MessagePasser` functionality with an `SSTORE` and corrects the value being stored.

Audit fix/message passer storage

---

contracts/optimistic-ethereum/OVM/execution/OVM_SafetyChecker.sol
test/data/json/safety-checker.test.json

Fixes a small bug in the safety checked logic where the input to `JUMPI` switched the `condition` and `destination`.

Fix JUMPI inputs ordering

---

contracts/optimistic-ethereum/OVM/chain/OVM_CanonicalTransactionChain.sol
contracts/optimistic-ethereum/iOVM/chain/iOVM_CanonicalTransactionChain.sol

Quick fix to make the queue index public for easy access.

Make getNextQueueIndex public

---

contracts/optimistic-ethereum/OVM/chain/OVM_CanonicalTransactionChain.sol
package.json
test/contracts/OVM/chain/OVM_CanonicalTransactionChain.spec.ts

Fixes a slight race condition where if you attempt to empty the queue with a number of elements that is larger than the total number of elements in the queue, you will have your tx revert. Because of this we had a mild race condition where if two people append queue batches, one might fail.
Additionally there was some weird behavior where you couldn't verify an element unless it was passed the force inclusion period. This isn't fatal but increases client complexity.

Allow easy emptying of the queue

---

src/contract-deployment/config.ts

Sets the sequencer key to `OVM_Sequencer`

deployment: register the sequencer address correctly

---

bin/deploy.js
package.json
src/contract-deployment/config.ts
src/contract-deployment/deploy.ts
src/contract-dumps.ts
yarn.lock

Adds deploy overrrides because of out of gas deployment issues when deploying to goerli, also allows a configurable xdomain messenger address.

feat: crossdomainmessenger address setup, deploy overrides

---

contracts/optimistic-ethereum/OVM/accounts/OVM_ECDSAContractAccount.sol
contracts/optimistic-ethereum/OVM/accounts/OVM_ProxyEOA.sol
contracts/optimistic-ethereum/OVM/precompiles/OVM_ProxySequencerEntrypoint.sol
contracts/optimistic-ethereum/OVM/precompiles/OVM_SequencerEntrypoint.sol
contracts/optimistic-ethereum/libraries/wrappers/Lib_SafeExecutionManagerWrapper.sol
contracts/optimistic-ethereum/mockOVM/accounts/mockOVM_ECDSAContractAccount.sol
test/contracts/OVM/execution/OVM_ExecutionManager/ovmCREATEEOA.spec.ts

This little PR removes the `_ovmExecutionManager` argument from `Lib_SafeExecutionManagerWrapper`, since the `evmCALLER` is the only acceptable parameter anyways.
N/A
- small code readability downside

remove msg.sender from all SafeEM calls

---

contracts/optimistic-ethereum/OVM/verification/OVM_BondManager.sol
contracts/optimistic-ethereum/OVM/verification/OVM_FraudVerifier.sol
contracts/optimistic-ethereum/iOVM/verification/iOVM_BondManager.sol
contracts/test-helpers/Mock_FraudVerifier.sol
test/bond.ts

- Deposits `requiredCollateral` every time
- Removes the `setRequiredCollateral` admin function. This removes the `owner` role from the contract (good!) and it also prevents inconsistencies which would require that we track more variables such as the ones described in https://github.com/ethereum-optimism/contracts-v2/commit/e57df4c638da8082741d070d5a355cabff0bab97 's commit message
- Removes the redundant `batchIndex` parameter
@kfichter @karlfloersch @ben-chain

Bond Manager Deposit bugfix

---

contracts/optimistic-ethereum/mockOVM/verification/mockOVM_BondManager.sol
src/contract-deployment/config.ts

Very simple PR, adds a `mockOVM_BondManager` to the deploy config as a temporary way to test the `OVM_StateCommitmentChain` without having to manually deploy a real `OVM_BondManager`.

Added mock bond manager to deploy config

---

contracts/optimistic-ethereum/OVM/verification/OVM_StateTransitioner.sol
test/bond.ts
test/contracts/OVM/accounts/OVM_ECDSAContractAccount.spec.ts
test/contracts/OVM/execution/OVM_StateManager.gas-spec.ts
test/contracts/OVM/execution/OVM_StateManager.spec.ts
test/contracts/OVM/verification/OVM_FraudVerifier.spec.ts
test/contracts/OVM/verification/OVM_StateTransitioner.spec.ts

Storage slot values are RLP-encoded before being inserted into the state trie. Our StateTransitioner currently does not account for this. Patch fixes this by RLP-decoding the values we get out and RLP-encoding them when we update.

Patches StateTransitioner to fix RLP-encoded storage slot values

---

contracts/optimistic-ethereum/OVM/verification/OVM_StateTransitioner.sol

Last PR was in error, `StateTransitioner` should only be decoding RLP values if the value actually existed.

Hotfix for decoding rlp values in state transitioner

---

contracts/optimistic-ethereum/OVM/execution/OVM_ExecutionManager.sol

This PR tackles OZ H06 (roadmap # 189).  TLDR: `ovmCALL` and `ovmCREATE` should get statically sized refunds, not dynamic refunds resulting in a static overall cost, since their subsequent gas consumption is itself quite dynamic.
- Not sure the best way to unit test this fix though it should definitely work.  Probably a generic gas refund test ticket to be broken out there.  @kfichter LMK if you have any ideas for robust testing of both of the modifiers.
- Fixes roadmap # 189

Static Refunds for ovmCALL; ovmCREATE

---

contracts/optimistic-ethereum/libraries/rlp/Lib_RLPWriter.sol
contracts/test-libraries/rlp/TestLib_RLPWriter.sol
test/contracts/libraries/rlp/Lib_RLPWriter.spec.ts

Adds a `_malloc` function for clearing memory at the free pointer, and adds a test which would fail for `writeAddress` without it.
Which functions need this applied? All of them?

Fix RLPWriter Memory Allocation

---

src/contract-dumps.ts

Instead of RLP decoding values from the storage trie, we were just slicing off the first byte. This works for most values, but values between `0x00` and 0x7f` are not prefixed when rlp encoding, so these values were getting wiped. 
- 
-
-

Fix rlp encoding bug in contract dump

---

contracts/optimistic-ethereum/mockOVM/accounts/mockOVM_ECDSAContractAccount.sol

Small PR to revert the chain ID assertion in our mock contract account.  Since this is used for things like `eth_call`, there's no need to authenticate.

Remove chainId check from mock account

---

package.json

Moves `ganache-core` to `dependencies` instead of `devDependencies`. Fixes #95.

Move ganache-core to main deps

---

contracts/optimistic-ethereum/OVM/bridge/OVM_L1CrossDomainMessenger.sol
test/contracts/OVM/bridge/OVM_L1CrossDomainMessenger.spec.ts

This PR adds a check in the `OVM_L1CrossDomainMessenger` to look up an `OVM_L2Relayer` address in the `AddressManager`.  If the address has been set, only the `OVM_L2Relayer` may call `OVM_L1CrossDomainMessenger.relayMessage()`.
- Fixes https://github.com/ethereum-optimism/roadmap/issues/160

Add OVM_L2Relayer Check to L1CrossDomainMessenger

---

contracts/optimistic-ethereum/OVM/chain/OVM_StateCommitmentChain.sol
contracts/optimistic-ethereum/iOVM/chain/iOVM_StateCommitmentChain.sol

Adds a simple `StateBatchDeleted` event so we can filter out state batches that have been deleted (for use within the fraud prover).

Add StateBatchDeleted event to SCC

---

contracts/optimistic-ethereum/mockOVM/verification/mockOVM_BondManager.sol
src/contract-deployment/config.ts
test/contracts/mockOVM/verification/mockOVM_BondManager.spec.ts

Previously our `mockOVM_BondManager` contract used for testing returned true for `isCollateralized` with any address.  This PR updates that to only return true for whatever the `OVM_Sequencer` address is set to resolve.
- Fixes https://github.com/ethereum-optimism/roadmap/issues/253

Update mockOVM_BondManager to be sequencer-only

---

contracts/optimistic-ethereum/OVM/chain/OVM_CanonicalTransactionChain.sol
contracts/optimistic-ethereum/OVM/chain/OVM_ChainStorageContainer.sol
contracts/optimistic-ethereum/OVM/chain/OVM_StateCommitmentChain.sol
contracts/optimistic-ethereum/iOVM/chain/iOVM_CanonicalTransactionChain.sol
contracts/optimistic-ethereum/iOVM/chain/iOVM_ChainStorageContainer.sol
contracts/optimistic-ethereum/iOVM/chain/iOVM_StateCommitmentChain.sol
contracts/optimistic-ethereum/libraries/utils/Lib_Math.sol
contracts/optimistic-ethereum/libraries/utils/Lib_RingBuffer.sol
contracts/test-libraries/utils/TestLib_RingBuffer.sol
package.json
src/contract-deployment/config.ts
src/contract-deployment/deploy.ts
test/contracts/OVM/chain/OVM_CanonicalTransactionChain.spec.ts
test/contracts/OVM/chain/OVM_StateCommitmentChain.spec.ts

Creates a new contract, `OVM_ChainStorageContainer`, which actually stores the values instead of doing it directly in the SCC and CTC.

Separates storage from SCC and CTC

---

contracts/optimistic-ethereum/OVM/chain/OVM_CanonicalTransactionChain.sol
test/contracts/OVM/chain/OVM_CanonicalTransactionChain.spec.ts

Disables `appendQueueBatch` at the contract level with a `revert`. Needs to skip a few tests, adds a test for the newly added revert

ctc: disable appendQueueBatch

---

contracts/optimistic-ethereum/OVM/chain/OVM_CanonicalTransactionChain.sol
src/contract-deployment/config.ts
test/contracts/OVM/chain/OVM_CanonicalTransactionChain.spec.ts

This little PR adds logic for the `OVM_CTC.enqueue` function to block transactions with oversized gas limits.
This is also already being done in the execution manager, but failing at the time of submission provides better UX.

Make gas-too-big transactions fail sooner

---

contracts/optimistic-ethereum/OVM/chain/OVM_CanonicalTransactionChain.sol
contracts/optimistic-ethereum/iOVM/chain/iOVM_CanonicalTransactionChain.sol

Small update to change back CTC interface to what is currently deployed for ease of testing.

Revert changes to CTC abi

---

contracts/optimistic-ethereum/OVM/execution/OVM_ExecutionManager.sol
contracts/optimistic-ethereum/OVM/verification/OVM_StateTransitioner.sol
test/contracts/OVM/execution/OVM_ExecutionManager/run.spec.ts
test/contracts/OVM/verification/OVM_StateTransitioner.spec.ts

Small fix moving the `gasleft()` check during transaction application out of the execution manager and into the State Transitioner.  This was causing a real headache in l2geth; this removes that issue from geth while still treating it properly for all possible L1 code paths.

Moves gas check to applyTransaction

---

test/contracts/OVM/precompiles/OVM_SequencerEntrypoint.spec.ts

I found some tests that were skipped, that can/should be re-activated.
This is a tiny PR, so seemed worth doing now.

Unskip tests that were waiting for an update to smock

---

contracts/optimistic-ethereum/libraries/utils/Lib_BytesUtils.sol
contracts/test-libraries/rlp/TestLib_RLPWriter.sol
contracts/test-libraries/utils/TestLib_BytesUtils.sol
test/contracts/libraries/rlp/Lib_RLPWriter.spec.ts
test/contracts/libraries/utils/Lib_BytesUtils.spec.ts

Fixes a bug where `Lib_BytesUtils.slice` would out-of-gas if asked for a slice of length `0` and memory was nonzero beyond where `0x40` points.
https://github.com/ethereum-optimism/roadmap/issues/393

Fix Memory Bug in bytes slice util

---

contracts/optimistic-ethereum/OVM/chain/OVM_CanonicalTransactionChain.sol

Removes unused `lastOVMTimestamp` and makes the constructor args public variables so that they can be fetched by users when constructing transactions. Also useful for the sequencer to configure its gas limit on L2

ctc: public getters, remove dead variable

---

contracts/optimistic-ethereum/OVM/bridge/OVM_BaseCrossDomainMessenger.sol
contracts/optimistic-ethereum/OVM/bridge/OVM_L1CrossDomainMessenger.sol
contracts/optimistic-ethereum/OVM/bridge/OVM_L2CrossDomainMessenger.sol

This is a fix to Sam's bug. 
> Additionally, @karlfloersch pointed out that another way to address this would be checking that the msg.sender == address(0), because this condition can only be satisfied at the first contract ovmCALLed by run.
- Fixes #105 
- Also https://github.com/ethereum-optimism/roadmap/issues/394 (private issue)

Add nonReentrant to `relayMessage()`

---

contracts/optimistic-ethereum/OVM/execution/OVM_ExecutionManager.sol

Adds reentrancy protection on `ExecutionManager.run()` by ensuring the `transactionContext` is uninitialized.
https://github.com/ethereum-optimism/roadmap/issues/400

Add reentry protection to ExecutionManager.run()

---

contracts/optimistic-ethereum/OVM/execution/OVM_ExecutionManager.sol

Fixes a little bug found by sam where nonces could be updated during an `ovmSTATICCALL`.  This does not pose a security risk because behavior will be consistent, but still worth fixing.

Adds `notStatic` modifier to `ovmSETNONCE`

---

bin/deploy.js
src/contract-deployment/deploy.ts

Fix single contract deployment

---

CHANGELOG.md
package.json

version: bump to 0.1.4

---

contracts/optimistic-ethereum/OVM/precompiles/OVM_SequencerEntrypoint.sol

- Fixes this dapp hub issue: https://github.com/ethereum-optimism/roadmap/issues/273
I noticed that the encoding order here (r,s,v) does not match what is used in Lib_ECDSAUtils (v,r,s), is that intentional?
https://github.com/ethereum-optimism/contracts-v2/blob/38fd27028f740d0bb01634e406f46fbaf47a369a/contracts/optimistic-ethereum/libraries/utils/Lib_ECDSAUtils.sol#L25

[WIP] Add missing comment

---

contracts/optimistic-ethereum/mockOVM/bridge/mockOVM_GenericCrossDomainMessenger.sol
package.json
yarn.lock

Adds a better mock contract for cross domain communications. Necessary so that we can do comms between two unique chains.

Add GenericCrossDomainMessenger (mock) for L1<>L2 testing

---

.github/workflows/integration.yml

Removes the dependency to use an ssh key that is stored as a github secret in CI. This enables outside contributors to run the integration tests.

ci: fix for outside contributors

---

package.json

We moved over to `hardhat`, which means that the structure of the `artifacts` folder has changed. As a result, our package.json is broken and our artifacts are not being included as part of the `build` folder published to `npm`. We need this update or we can't use any artifacts from our latest contract versions.

Fix package json so the build actually works

---

.github/workflows/integration.yml

This should fix the ability for the CI to properly run during PRs from forks of the repo

gitflows: easily allow outside contributors

---

contracts/optimistic-ethereum/OVM/chain/OVM_CanonicalTransactionChain.sol
contracts/optimistic-ethereum/OVM/chain/OVM_ChainStorageContainer.sol
contracts/optimistic-ethereum/iOVM/chain/iOVM_CanonicalTransactionChain.sol

Adds getters for the Canonical Transaction Chain extradata. These 2 methods could be bundled together into a single method if that is preferable. This is useful information and also helpful for debugging. I could imagine contracts spanning L1 and L2 wanting to be able to know this information. Right now the only way to get this information is through `ChainStorageContainer.getGlobalMetadata` and then deserializing by hand

feat: getters for ctc extradata

---

bin/serve_dump.sh
package.json

A script for serving the state dump on localhost. Usage:
```bash
$ yarn build
$ yarn serve
```
This depends on python3 being installed locally

script: serve state dump

---

contracts/optimistic-ethereum/OVM/bridge/tokens/OVM_L1ERC20Gateway.sol

The variable names in `OVM_L1ERC20Gateway.sol` were still referring to the L2 contract as `l2ERC20Gateway`.

Update naming: l2ERC20Gateway -> l2DepositedERC20

---

contracts/optimistic-ethereum/OVM/execution/OVM_ExecutionManager.sol

This was bricking the js-vm sometimes;

Reset Context on invalid gaslimit

---

contracts/optimistic-ethereum/OVM/bridge/tokens/Abs_L1TokenGateway.sol
contracts/optimistic-ethereum/OVM/bridge/tokens/Abs_L2DepositedToken.sol
contracts/optimistic-ethereum/iOVM/bridge/tokens/iOVM_L1TokenGateway.sol
contracts/optimistic-ethereum/iOVM/bridge/tokens/iOVM_L2DepositedToken.sol

Early user feedback suggests this results in more pain than gain, so this makes the gas estimators optional.

Remove gas estimators from gateway interface

---

hardhat.config.ts
package.json
yarn.lock

`hardhat-typechain` moved over to `@typechain/hardhat`. The (wonderful) maintainers over there also just published a new release after patching an issue we had with the plugin: https://github.com/ethereum-ts/TypeChain/pull/341 so our TypeChain outputs are working again. I went ahead and added the TypeChain outputs to the package.json too (although I'm not sure if this is strictly necessary).
- Any thoughts on having the TypeChain outputs in the npm package?
- Fixes #295

dev: Update TypeChain usage

---

contracts/optimistic-ethereum/OVM/execution/OVM_ExecutionManager.sol

This allows deployed code to be correctly returned by geth in L2 during `eth_call`.

Fix simulateMessage for eth_calls

---

contracts/optimistic-ethereum/OVM/chain/OVM_CanonicalTransactionChain.sol
contracts/optimistic-ethereum/OVM/chain/OVM_ChainStorageContainer.sol
contracts/optimistic-ethereum/iOVM/chain/iOVM_ChainStorageContainer.sol
contracts/optimistic-ethereum/libraries/utils/Lib_RingBuffer.sol
contracts/test-libraries/utils/TestLib_RingBuffer.sol

Push2 is a solidity opcode, so we want to make sure that there is clear differentiation between the opcode and function names. This PR renames all instances of push2 to pushTwo and get2 to getTwo.
- Fixes #318

Rename all instances of push2 to pushTwo and get2 to getTwo

---

contracts/optimistic-ethereum/OVM/bridge/messaging/Abs_BaseCrossDomainMessenger.sol
contracts/optimistic-ethereum/OVM/bridge/messaging/OVM_L2CrossDomainMessenger.sol
contracts/optimistic-ethereum/OVM/bridge/tokens/Abs_L1TokenGateway.sol
contracts/optimistic-ethereum/OVM/bridge/tokens/Abs_L2DepositedToken.sol
contracts/optimistic-ethereum/OVM/bridge/tokens/OVM_L1ERC20Gateway.sol
contracts/optimistic-ethereum/OVM/bridge/tokens/OVM_L2DepositedERC20.sol
contracts/optimistic-ethereum/OVM/chain/OVM_CanonicalTransactionChain.sol
contracts/optimistic-ethereum/OVM/execution/OVM_ExecutionManager.sol
contracts/optimistic-ethereum/libraries/standards/UniswapV2ERC20.sol
contracts/optimistic-ethereum/libraries/utils/Lib_RingBuffer.sol
contracts/optimistic-ethereum/mockOVM/accounts/mockOVM_ECDSAContractAccount.sol
contracts/optimistic-ethereum/mockOVM/bridge/mockOVM_GenericCrossDomainMessenger.sol
contracts/optimistic-ethereum/mockOVM/verification/mockOVM_BondManager.sol
contracts/test-helpers/Helper_ModifiableStorage.sol
contracts/test-helpers/Helper_PrecompileCaller.sol
contracts/test-helpers/Helper_SimpleProxy.sol
contracts/test-helpers/Helper_TestRunner.sol

Clears compiler warnings when compiling contracts. Each warning type is addressed within a single commit in this PR.
- I wasn't sure if I addressed `Warning: Unnamed return variable can remain unassigned.` correctly. Specifically, I took out a return for one of the functions because it was not being used.
- For `unused local variable warning`, I took out a couple of local variables for calculating `gasUsed` which was not being used in the function. Is that okay?
- Fixes #255

fix: Clear Compiler Warnings

---

contracts/optimistic-ethereum/OVM/chain/OVM_CanonicalTransactionChain.sol
contracts/optimistic-ethereum/OVM/chain/OVM_ChainStorageContainer.sol
contracts/optimistic-ethereum/iOVM/chain/iOVM_ChainStorageContainer.sol
contracts/optimistic-ethereum/libraries/utils/Lib_RingBuffer.sol
contracts/test-libraries/utils/TestLib_RingBuffer.sol

Current Chain storage containers on Kovan and Mainnet don't have pushTwo or getTwo, and they add a bit of complexity, so let's just remove them for now. The gas savings are minimal according to @smartcontracts, so I think we should be good there.
- 
-
-

remove pushTwo and getTwo

---

package.json
test/contracts/OVM/chain/OVM_CanonicalTransactionChain.gas.spec.ts
test/contracts/OVM/chain/OVM_CanonicalTransactionChain.spec.ts
yarn.lock

Noticed we have `core-utils` listed twice. Seems like the tests fail when removing the older one.

build: remove duplicate npm dependency

---

package.json

Move `@eth-optimism/dev` to dev dependencies. Right now installing this package installs mocha and tons of other not needed crap :O

Move `@eth-optimism/dev` to dev dependencies

---

contracts/optimistic-ethereum/libraries/rlp/Lib_RLPReader.sol
test/data/json/libraries/rlp/Lib_RLPReader.test.json

Minor fix, handles an issue pointed out by proto. Geth is much stricter than `Lib_RLPReader` about checking the validity of boolean values. This PR fixes that discrepancy and explicitly checks that the boolean value is either 0 or 1.
**Metadata**
- Fixes proto#42

fix: Stricter RLP boolean checking

---

contracts/optimistic-ethereum/libraries/resolver/Lib_AddressResolver.sol

The `libAddressManager` variable is currently internal and isn't easily accessible from the outside. Ideally this variable should be public so we have more visibility into the state of our contracts. Particularly important for doing post-deployment verification for proxies (which are initialized outside of the constructor).

Make the libAddressManager variable public

---

deploy/001-OVM_ChainStorageContainer_ctc_batches.deploy.ts
deploy/002-OVM_ChainStorageContainer_ctc_queue.deploy.ts
deploy/003-OVM_ChainStorageContainer_scc_batches.deploy.ts
deploy/004-OVM_CanonicalTransactionChain.deploy.ts
deploy/005-OVM_StateCommitmentChain.deploy.ts
deploy/006-OVM_ExecutionManager.deploy.ts
deploy/007-OVM_FraudVerifier.deploy.ts
deploy/008-mockOVM_BondManager.deploy.ts
deploy/009-OVM_SafetyChecker.deploy.ts
deploy/010-OVM_StateManagerFactory.deploy.ts
deploy/011-OVM_StateTransitionerFactory.deploy.ts
deploy/012-OVM_L1MultiMessageRelayer.deploy.ts
src/hardhat-deploy-ethers.ts

As title, should make the https://github.com/ethereum-optimism/contracts/pull/249 more easy to review. 
This can be abstracted a bit more on the proxies. 
Q: Why are we using a mock ovm bond manager?

Refactor repeatable hh-deploy code to helper function

---

contracts/optimistic-ethereum/libraries/utils/Lib_MerkleTree.sol

While reviewing the code from a project that uses the same `Lib_MerkleTree` library you're using, I noticed a sub-optimal loop iterator using `uint8` instead of `uint256`.
Because of this, Solidity will generate more operations to make sure the iterator stays within the `uint8` constraints, hence it will cost more gas to execute the loop.
I created a Solidity contract and ran a few tests which might help you decide if you want to include the change or not.
The following Solidity contract example was used to measure the difference between using `uint8` and `uint256` with a few example inputs.
```solidity
contract FindBit {
function find_highest_set_bit(
uint value
) 
public 
pure 
returns (
uint
) 
{
uint _in = value;
if (_in == 1) {
return 0;
}
// Find the highest set bit …
```

Optimize loop iterator in `Lib_MerkleTree.sol`.

---

contracts/optimistic-ethereum/OVM/execution/OVM_ExecutionManager.sol

Previously we were resetting the SM address at the end of `run()`. In the case that the `_isValidGasLimit` check fails, this would result in the SM address remaining set, which breaks the invariant that the EM state should remain constant before and after a call to `run()`.

Treat SM address as context

---

contracts/optimistic-ethereum/OVM/verification/OVM_StateTransitioner.sol

Fixes: https://github.com/ethereum-optimism/roadmap/issues/817
This disallows an evil state manager attack.

Prevent EM from calling SM after applyTransaction()

---

contracts/optimistic-ethereum/OVM/chain/OVM_CanonicalTransactionChain.sol
test/contracts/OVM/chain/OVM_CanonicalTransactionChain.spec.ts

`MAX_ROLLUP_TX_SIZE` was enforced on `enqueue()` but not on `appendSequencerBatch()`.

Enforce MAX_ROLLUP_TX_SIZE on sequencer tx

---

contracts/optimistic-ethereum/OVM/bridge/messaging/OVM_L1CrossDomainMessenger.sol
contracts/optimistic-ethereum/OVM/bridge/messaging/OVM_L2CrossDomainMessenger.sol
contracts/optimistic-ethereum/OVM/execution/OVM_ExecutionManager.sol
test/contracts/OVM/bridge/base/OVM_L2CrossDomainMessenger.spec.ts

This change prevents call spoofing on L2.
Adds a test based on logs and successfulMessages mapping.

Disallow relayMessage to L2 to L1 Message Passer

---

contracts/optimistic-ethereum/OVM/chain/OVM_CanonicalTransactionChain.sol
test/contracts/OVM/chain/OVM_CanonicalTransactionChain.spec.ts

Bumps the MAX_ROLLUP_TX_SIZE to a more reasonable value so that the new enforcement on sequencer transactions still allows things like large contract deployments.

fix: increase MAX_ROLLUP_TX_SIZE

---

package.json

Locks the smock version to pre-empt an upcoming breaking change to the interface.

Lock smock version
